const vm = Vue.createApp({
    data(){
        return{
            birds:['Pigeons','Eagels','Doves','Parrots'],
            people:[
                {
                name:'John',
                age:20,
                },
                {
                 name:'Rick',
                 age:18,
                },
                {
                 name:'Amy',
                 age:33,
                }
            ]
        }
    }
}).mount('#app')